services:
  protonmail-bridge:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: pm_bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
